// This file was generated by Genii HTML Builder
import {
  Container,
  Text,
  Custom1,
  Custom2,
  Custom3,
} from '@material-ui/core';
import { makeStyles } from '@material-ui/core/styles';

const useStyles = makeStyles({
  Container_470: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '40px 40px 40px 40px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(255, 255, 255, 1)',
    color: 'rgba(0, 0, 0, 1)',
    width: '800px',
    height: 'auto',
  },
  Container_9951: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '40px 40px 40px 40px',
    margin: '0px 0px 40px 0px',
    background: 'rgba(255, 255, 255, 1)',
    color: 'rgba(0, 0, 0, 1)',
    width: '100%',
    height: 'auto',
  },
  Container_7503: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '0px 20px 0px 20px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(255, 255, 255, 1)',
    color: 'rgba(0, 0, 0, 1)',
    width: '40%',
    height: '100%',
  },
  Text_7024: {
    fontSize: '23',
    textAlign: 'left',
    fontWeight: '400',
    color: 'rgba(92, 90, 90, 1)',
    margin: '0px 0px 0px 0px',
    text: 'Craft.js is a React framework for building powerful & feature-rich drag-n-drop page editors.',
  },
  Container_182: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '0px 20px 0px 20px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(255, 255, 255, 1)',
    color: 'rgba(0, 0, 0, 1)',
    width: '60%',
    height: '100%',
  },
  Text_9600: {
    fontSize: '14',
    textAlign: 'left',
    fontWeight: '400',
    color: 'rgba(92, 90, 90, 1)',
    margin: '0px 0px 0px 0px',
    text: 'Everything you see here, including the editor, itself is made of React components. Craft.js comes only with the building blocks for a page editor; it provides a drag-n-drop system and handles the way user components should be rendered, updated and moved, among other things. <br /> <br /> You control the way your editor looks and behave.',
  },
  Container_3302: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '40px 40px 40px 40px',
    margin: '0px 0px 40px 0px',
    background: 'rgba(39, 41, 41, 1)',
    color: 'rgba(0, 0, 0, 1)',
    width: '100%',
    height: 'auto',
  },
  Container_2259: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '0px 0px 0px 0px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(76, 78, 78, 0)',
    color: 'rgba(0, 0, 0, 1)',
    width: '100%',
    height: 'auto',
  },
  Container_2814: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '0px 0px 0px 0px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(0, 0, 0, 0)',
    color: 'rgba(0, 0, 0, 1)',
    width: '350px',
    height: '250px',
  },
  Container_2172: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    fillSpace: 'no',
    padding: '10px 20px 10px 20px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(76, 78, 78, 1)',
    color: 'rgba(0, 0, 0, 1)',
    shadow: '25',
    width: '90%',
    height: '90%',
  },
  Container_1201: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    fillSpace: 'no',
    padding: '10px 20px 10px 20px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(76, 78, 78, 1)',
    color: 'rgba(0, 0, 0, 1)',
    shadow: '50',
    width: '80%',
    height: '80%',
  },
  Container_1775: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    fillSpace: 'no',
    padding: '10px 20px 10px 20px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(76, 78, 78, 1)',
    color: 'rgba(0, 0, 0, 1)',
    shadow: '50',
    width: '60%',
    height: '60%',
  },
  Container_2340: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'yes',
    padding: '0px 0px 0px 20px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(0, 0, 0, 0)',
    color: 'rgba(0, 0, 0, 1)',
    width: '55%',
    height: '100%',
  },
  Text_2953: {
    fontSize: '20',
    textAlign: 'left',
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 1)',
    margin: '0px 0px 18px 0px',
    text: 'Design complex components',
  },
  Text_6557: {
    fontSize: '14',
    textAlign: 'left',
    fontWeight: '400',
    color: 'rgba(255, 255, 255, 0.8)',
    margin: '0px 0px 0px 0px',
    text: 'You can define areas within your React component which users can drop other components into. <br/><br />You can even design how the component should be edited — content editable, drag to resize, have inputs on toolbars — anything really.',
  },
  Container_3211: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '40px 40px 40px 40px',
    margin: '0px 0px 40px 0px',
    background: 'rgba(234, 245, 245, 1)',
    color: 'rgba(0, 0, 0, 1)',
    width: '100%',
    height: 'auto',
  },
  Container_6706: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '0px 0px 0px 0px',
    margin: '0,px 0px 20px 0px',
    background: 'rgba(76, 78, 78, 0)',
    color: 'rgba(0, 0, 0, 1)',
    width: '100%',
    height: 'auto',
  },
  Text_2971: {
    fontSize: '23',
    textAlign: 'left',
    fontWeight: '500',
    color: 'rgba(46, 47, 47, 1)',
    margin: '0px 0px 0px 0px',
    text: 'Programmatic drag & drop',
  },
  Text_3644: {
    fontSize: '14',
    textAlign: 'left',
    fontWeight: '400',
    color: 'rgba(92, 90, 90, 1)',
    margin: '0px 0px 0px 0px',
    text: 'Govern what goes in and out of your components',
  },
  Container_3500: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '0px 0px 0px 0px',
    margin: '30px 0px 0px 0px',
    background: 'rgba(76, 78, 78, 0)',
    color: 'rgba(0, 0, 0, 1)',
    width: '100%',
    height: 'auto',
  },
  Container_9230: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '0px 20px 0px 0px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(0, 0, 0, 0)',
    color: 'rgba(0, 0, 0, 1)',
    width: '45%',
    height: 'auto',
  },
  Custom1_9086: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '20px 20px 20px 20px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(119, 219, 165, 1)',
    color: 'rgba(0, 0, 0, 1)',
    shadow: '40',
    width: '100%',
    height: 'auto',
  },
  Container_861: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '0px 0px 0px 20px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(0, 0, 0, 0)',
    color: 'rgba(0, 0, 0, 1)',
    width: '55%',
    height: 'auto',
  },
  Custom2_352: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '0px 0px 0px 20px',
    margin: '0px 0px 0px 0px',
    background: 'rgba(108, 126, 131, 1)',
    color: 'rgba(0, 0, 0, 1)',
    shadow: '40',
    width: '100%',
    height: '125px',
  },
  Custom3_8360: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    fillSpace: 'no',
    padding: '20px 20px 20px 20px',
    margin: '20px 0px 0px 0px',
    background: 'rgba(134, 187, 201, 1)',
    color: 'rgba(0, 0, 0, 1)',
    shadow: '40',
    width: '100%',
    height: 'auto',
  },
});

function Home(props) {
  const classes = useStyles(props);

  return (
    <>
      <Container className={classes.Container_470}>
        <Container className={classes.Container_9951}>
          <Container className={classes.Container_7503}>
            <Text className={classes.Text_7024}>
              Craft.js is a React framework for building powerful & feature-rich drag-n-drop page editors.
            </Text>
          </Container>
          <Container className={classes.Container_182}>
            <Text className={classes.Text_9600}>
              Everything you see here, including the editor, itself is made of React components. Craft.js comes only with the building blocks for a page editor; it provides a drag-n-drop system and handles the way user components should be rendered, updated and moved, among other things. <br /> <br /> You control the way your editor looks and behave.
            </Text>
          </Container>
        </Container>
        <Container className={classes.Container_3302}>
          <Container className={classes.Container_2259}>
            <Container className={classes.Container_2814}>
              <Container className={classes.Container_2172}>
                <Container className={classes.Container_1201}>
                  <Container className={classes.Container_1775} />
                </Container>
              </Container>
            </Container>
            <Container className={classes.Container_2340}>
              <Text className={classes.Text_2953}>
                Design complex components
              </Text>
              <Text className={classes.Text_6557}>
                You can define areas within your React component which users can drop other components into. <br/><br />You can even design how the component should be edited — content editable, drag to resize, have inputs on toolbars — anything really.
              </Text>
            </Container>
          </Container>
        </Container>
        <Container className={classes.Container_3211}>
          <Container className={classes.Container_6706}>
            <Text className={classes.Text_2971}>
              Programmatic drag & drop
            </Text>
            <Text className={classes.Text_3644}>
              Govern what goes in and out of your components
            </Text>
          </Container>
          <Container className={classes.Container_3500}>
            <Container className={classes.Container_9230}>
              <Custom1 className={classes.Custom1_9086} />
            </Container>
            <Container className={classes.Container_861}>
              <Custom2 className={classes.Custom2_352} />
              <Custom3 className={classes.Custom3_8360} />
            </Container>
          </Container>
        </Container>
      </Container>
    </>
  );
};

export default Home;
