// This file was generated by Genii HTML Builder
import {
  Container,
  Typography,
  Button,
} from '@material-ui/core';
import { makeStyles } from '@material-ui/core/styles';

const useStyles = makeStyles({
  Typography_893: {
    fontSize: '12',
    textAlign: 'left',
    fontWeight: '500',
    shadow: '0',
  },
  Button_9432: {
  },
  Typography_3958: {
    fontSize: '12',
    textAlign: 'left',
    fontWeight: '500',
    shadow: '0',
  },
});

function Home(props) {
  const classes = useStyles(props);

  return (
    <>
      <Container >
        <Typography className={classes.Typography_893} color='primary' display='initial' variant='body1' align='justify'>
          Hi there
        </Typography>
        <Button className={classes.Button_9432} size='medium' variant='outlined' color='secondary'>
          Button
        </Button>
        <Typography className={classes.Typography_3958} color='secondary' display='initial' variant='h2' align='left'>
          Hi there
        </Typography>
      </Container>
    </>
  );
};

export default Home;
